BukzineMagentoBundle:
    resource: "@BukzineMagentoBundle/Resources/config/routing.yml"
    prefix:   /magento

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
