services:
    magento.collection.subscriber:
        class: Bukzine\MagentoBundle\Subscriber\MagentoCollectionSubscriber
        scope: request
        tags:
            - { name: knp_paginator.subscriber }